spring.application.name=SumativaCloudNative
server.port=8080

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG


# Configuracion EFS
efs.path=/app/efs
aws.s3.bucket=${S3_BUCKET_NAME}